site_name: Uni Noter
site_author: Mathias Andresen
site_url: http://notes.andresen.xyz/
repo_name: 'jollycola/uni-notes'
repo_url: 'https://gitlab.com/jollycola/uni-notes'


theme:
    name: 'material'
    font: 
        text: 'Open Sans'
        code: 'Roboto Mono'
    logo:
        icon: 'school'
    feature:
        tabs: true


extra_css:
  - 'stylesheets/github.css'
  - 'stylesheets/github.user.css'
  - 'stylesheets/extra.css'


extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.emoji