site_name: Mathias Andresen's Uni Noter
site_url: https://jollycola.gitlab.io/uni-notes/

nav:
    - Home: index.md


theme:
    name: 'material'
    logo:
        icon: 'dns'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true