site_name: Mathias Andresen's Uni Noter
site_url: https://jollycola.gitlab.io/uni-notes/
repo_name: 'jollycola/uni-notes'
repo_url: 'https://gitlab.com/ollycola/uni-notes'


theme:
    name: 'material'
    logo:
        icon: 'dns'


extra_css:
  - 'stylesheets/extra.css'


extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex